apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerport}}
      protocol: TCP
      name: {{ .Values.backend.name }}
    - port: {{ .Values.backend.service.debugport }}
      targetPort: {{ .Values.backend.debugport}}
      protocol: TCP
      name: {{ .Values.backend.name }}-debug
  selector:
    app: {{ .Values.backend.name }}
