apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    server:
      host: 0.0.0.0
      port: {{ .Values.backend.containerport }}
      log_level: {{ .Values.backend.config.log_level | quote }}
      allowed_origins: ["*"]
