apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
data:
  application-ewc-dev.yaml: |
    server:
      port: {{ .Values.backend.containerport }}

    keycloak:
      url: {{ .Values.backend.keycloak_cluster_url }}
      realm: {{ .Values.keycloak_realm }}

    vault:
      endpoint: {{ .Values.backend.vault_url }}
      scheme: http
      port: {{ .Values.backend.vault_port }}
      token: {{ .Values.backend.vault_token }}
      path: {{ .Values.backend.vault_path }}

    apisix:
      #baseUrl: http://apisix:9180 #this is for docker
      adminUrl: {{ .Values.backend.apisix_admin_url }}
      gatewayUrl: {{ .Values.backend.apisix_gateway_url }} 
      consumersUrl: ${apisix.adminUrl}/apisix/admin/consumers
      routesUrl: ${apisix.adminUrl}/apisix/admin/routes
      adminApiKey: {{ .Values.backend.apisix_apikey }}
      keyPath: {{ .Values.backend.apisix_keypath }}
      keyName: {{ .Values.backend.apisix_keyname }}


    management:
      metrics:
        tags:
          application: devportal-backend
