{{- if (not .Values.backend.secrets.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  secrets.yaml: |
    vault:
      base_path: {{ .Values.backend.secrets.vault_path }}
      secret_phase: {{ randAscii 32 | quote }}
      instances:
        {{- range .Values.backend.secrets.vault_instances }}
          - name: {{ .name }}
            token: {{ .token }}
            url: {{ .url }}
        {{- end}}

    apisix:
      key_path: {{ .Values.backend.secrets.apisix_keypath }}
      global_gateway_url: {{ .Values.backend.secrets.apisix_gateway_url }}
      instances:
        {{- range .Values.backend.secrets.apisix_instances }}
          - name: {{ .name }}
            admin_url: {{ .admin_url }}
            admin_api_key: {{ .admin_api_key }}
        {{- end}}

    keycloak:
      url: {{ .Values.backend.config.keycloak_cluster_url }}
      realm: {{ .Values.keycloak_realm }}
      client_id: {{ .Values.backend.secrets.keycloak_client_id }}
      client_secret: {{ .Values.backend.secrets.keycloak_client_secret }}
{{- end }}
