apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    server:
      host: {{ .Values.ingress.host }} 
      port: {{ .Values.backend.containerport }}
      log_level: INFO

    keycloak:
      url: {{ .Values.backend.keycloak_cluster_url }}
      realm: {{ .Values.keycloak_realm }}

    vault:
      url: {{ .Values.backend.vault_url }}
      token: {{ .Values.backend.vault_token }}
      base_path: {{ .Values.backend.vault_path }}
      secret_phase: {{ .Values.backend.vault_phase }}

    apisix:
      admin_url: {{ .Values.backend.apisix_admin_url }}
      gateway_url: {{ .Values.backend.apisix_gateway_url }} 
      admin_api_key: {{ .Values.backend.apisix_apikey }}
      key_path: {{ .Values.backend.apisix_keypath }}
