{{- if (not .Values.backend.secrets.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  secrets.yaml: |
    vault:
      url: {{ .Values.backend.secrets.vault_url }}
      token: {{ .Values.backend.secrets.vault_token }}
      base_path: {{ .Values.backend.secrets.vault_path }}
      secret_phase: {{ .Values.backend.secrets.vault_phase }}

    apisix:
      key_path: {{ .Values.backend.secrets.apisix_keypath }}
      instances:
        {{- range .Values.backend.secrets.apisix_instances }}
          - name: {{ .name }}
            admin_url: {{ .admin_url }}
            gateway_url: {{ .gateway_url }}
            admin_api_key: {{ .admin_api_key }}
        {{- end}}
{{- end }}
