{{- if (not .Values.backend.config.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.yaml: |
    server:
      port: {{ .Values.backend.containerport }}
      log_level: INFO

    keycloak:
      url: {{ .Values.backend.config.keycloak_cluster_url }}
      realm: {{ .Values.keycloak_realm }}

    vault:
      url: {{ .Values.backend.config.vault_url }}
      token: {{ .Values.backend.config.vault_token }}
      base_path: {{ .Values.backend.config.vault_path }}
      secret_phase: {{ .Values.backend.config.vault_phase }}

    apisix:
      admin_url: {{ .Values.backend.config.apisix_admin_url }}
      gateway_url: {{ .Values.backend.config.apisix_gateway_url }} 
      admin_api_key: {{ .Values.backend.config.apisix_apikey }}
      key_path: {{ .Values.backend.config.apisix_keypath }}
{{- end }}
