apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }} 
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }} 
    spec:
      containers:
      - name: {{ .Values.frontend.name }} 
        {{- if .Values.imageCredentials.enabled }}
        image: {{ .Values.imageCredentials.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        {{- else }}
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        {{- end }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.containerport }}
        volumeMounts:
        - name: env-file
          mountPath: "/portal-ui/dist/env-config.js"
          subPath: "env-config.js"
      {{- if .Values.imageCredentials.enabled }}
      imagePullSecrets:
      - name: registrykey
      {{- end }}
      volumes:
      - name: env-file
        configMap: 
          name: frontend-config 

