server:
  host: 0.0.0.0
  port: 8082
  log_level: "DEBUG"
  allowed_origins: ["*"]

status:
  services:
    - name: "MeteoGate Website"
      url: "https://meteogate.eu/"
    - name: "Open Radar Data (ORD)"
      url: "https://api.meteogate.eu/eu-eumetnet-weather-radar/health"
    - name: "Warnings API"
      url: "https://api.meteogate.eu/warnings/conformance"
    - name: "Surface observation API"
      url: "https://api.meteogate.eu/eu-eumetnet-surface-observations/health"
    - name: "Climate Data API"
      url: "https://api.meteogate.eu/eu-eumetnet-climate-observations/v1/health"
