# Default values for dev-portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imageCredentials:
  enabled: true
  registry: "ghcr.io"
  username: ""
  password: ""
backend:
  name: dev-portal-backend
  image:
    repository: eurodeo/dev-portal/backend
    pullPolicy: IfNotPresent
    tag: latest
  replicaCount: 2
  containerport: 8082
  service:
    type: ClusterIP
    port: 80
  config:
    log_level: INFO
    keycloak_cluster_url: http://keycloak.keycloak.svc.cluster.local
  secrets:
    # Provide a existing secret. If empty, one is created
    secretName: ""
    vault_path: apisix-dev/consumers
    vault_instances:
      - name: "EWC"
        token: ""
        url: "http://vault.vault.svc.cluster.local:8200"
    apisix_keypath: "$secret://vault/dev/"
    apisix_instances:
      - name: "EWC"
        admin_url: "http://apisix-admin.apisix.svc.cluster.local:9180"
        gateway_url: "http://apisix-gateway.apisix.svc.cluster.local"
        admin_api_key: ""
    keycloak_client_id: "dev-portal-api"
    keycloak_client_secret: ""
  readinessProbe:
    enabled: true
    initialDelaySeconds: 2
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

frontend:
  name: dev-portal-frontend
  image:
    repository: eurodeo/dev-portal/ui
    pullPolicy: IfNotPresent
    tag: latest
  replicaCount: 2
  containerport: 443
  service:
    type: ClusterIP
    port: 80
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  keycloak_url: "http://localhost:8080"
  keycloak_logout_url: "http://localhost"

keycloak_realm: test

ingress:
  enabled: false
  className: nginx
  annotations: 
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: localhost
    external-dns.alpha.kubernetes.io/target: 127.0.0.1
  host: localhost
  tls: 
    - secretName: devportal-tls
      hosts:
        - localhost
