# Default values for dev-portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  name: dev-portal-backend
  image:
    repository: joonahalonencgi/eurodeo-dev-portal-backend
    pullPolicy: IfNotPresent
    tag: latest
  replicaCount: 2
  containerport: 8082
  service:
    type: ClusterIP
    port: 80
  config:
    log_level: INFO
    keycloak_cluster_url: http://keycloak.keycloak.svc.cluster.local
  secrets:
    # Provide a existing secret. If empty, one is created
    secretName: ""
    vault_url: "http://vault.vault.svc.cluster.local:8200"
    vault_token: ""
    vault_path: apisix-dev/consumers
    apisix_keypath: "$secret://vault/dev/"
    apisix_instances:
      - name: "EWC"
        admin_url: "http://apisix-admin.apisix.svc.cluster.local:9180"
        gateway_url: "https://apisixdev.eumetnet-femdi.eumetsat.ewcloud.host"
        admin_api_key: ""
      - name: "AWS"
        admin_url: "https://apisixdev.devlyfe.fi:9180"
        gateway_url: "https://apisixdev.devlyfe.fi"
        admin_api_key: ""
    keycloak_client_id: "dev-portal-api"
    keycloak_client_secret: ""
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5

frontend:
  name: dev-portal-frontend
  image:
    repository: joonahalonencgi/eurodeo-dev-portal-frontend
    pullPolicy: IfNotPresent
    tag: latest
  replicaCount: 2
  containerport: 443
  service:
    type: ClusterIP
    port: 80

keycloak_url: "https://keycloak-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host"
keycloak_logout_url: "https://devportal-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host"
keycloak_realm: test

ingress:
  enabled: true
  className: nginx
  annotations: 
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    external-dns.alpha.kubernetes.io/hostname: devportal-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host
    external-dns.alpha.kubernetes.io/target: 64.225.132.246
  host: devportal-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host
  tls: 
    - secretName: devportal-tls
      hosts:
        - devportal-apisixdev.eumetnet-femdi.eumetsat.ewcloud.host
