server:
  port: 8082

keycloak:
  url: http://localhost:8080
  #url: http://auth:8080 #this is for docker
  realm: test

vault:
  endpoint: 127.0.0.1
  #endpoint: vault #this is for docker
  scheme: http
  port: 8200
  token: 00000000-0000-0000-0000-000000000000

apisix:
  consumersUrl: http://127.0.0.1:9180/apisix/admin/consumers
  #consumersUrl: http://apisix:9180/apisix/admin/consumers #this is for docker
  adminApiKey: edd1c9f034335f136f87ad84b625c8f1
  keyPath: $secret://vault/1/
  keyName: api-key


management:
  metrics:
    tags:
      application: devportal-backend