server:
  port: 8082

keycloak:
  url: http://localhost:8080
  #url: http://auth:8080 #this is for docker
  realm: test

vault:
  endpoint: 127.0.0.1
  #endpoint: vault #this is for docker
  scheme: http
  port: 8200
  token: 00000000-0000-0000-0000-000000000000
  path: apisix/

apisix:
  #baseUrl: http://apisix:9180 #this is for docker
  adminUrl: http://127.0.0.1:9180
  gatewayUrl: http://127.0.0.1:9080
  consumersUrl: ${apisix.adminUrl}/apisix/admin/consumers
  routesUrl: ${apisix.adminUrl}/apisix/admin/routes
  adminApiKey: edd1c9f034335f136f87ad84b625c8f1
  keyPath: $secret://vault/1/
  keyName: api-key


management:
  metrics:
    tags:
      application: devportal-backend