server:
  port: 9000

keycloak:
  #url: http://localhost:8080
  url: http://auth:8080/realms/test/protocol/openid-connect/certs #this is for docker
  realm: test

management:
  metrics:
    tags:
      application: devportal-backend