name: "Backend: test, build and publish docker image to registry"

env:
  DOCKER_REPO_NAME: eurodeo-dev-portal-backend

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - backend/**

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Start external services stack
          run: docker compose -f docker-compose.yml up -d --wait
        
        - name: Install Poetry
          run: curl -sSL https://install.python-poetry.org | python3 -

        - name: Set up Python environment
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            cache: 'poetry'
          
        - name: Install dependencies
          run: poetry install
          working-directory: ./backend

        - name: Run format Black
          run: poetry run black app/ --check
          working-directory: ./backend

        - name: Run Pylint
          run: poetry run pylint app/
          working-directory: ./backend
        
        - name: Run Mypy
          run: poetry run mypy app/
          working-directory: ./backend

        - name: Run Bandit
          run: poetry run bandit -r app
          working-directory: ./backend

        - name: Generate app configuration file for tests
          run: ./generate_config-yaml.sh > ./config.yaml
          working-directory: ./backend

        - name: Run tests
          run: poetry run pytest
          working-directory: ./backend

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        file: backend/Dockerfile
        context: ./backend
        push: true
        # for now cache to github actions
        # might need some tuning
        cache-from: type=gha 
        cache-to: type=gha,mode=max
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPO_NAME }}:latest
        #secret-files: |
        #  files here if any
